import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, CheckCircle2, Home as HomeIcon, Loader2, MapPin, Search, ShieldCheck, UserRound, Wrench, X } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { AppScreen, Worker } from '../types';
import { PUNCHX_50_CATEGORIES } from '../data/categories';
import { getCatalogCategory } from '../data/serviceCatalogs';
import PUNCHX_LOGO from '../assets/logo';
import { getAccurateCurrentPosition, reverseGeocodeCoords } from '../lib/location';

interface Props { onTransition:(target:AppScreen)=>void; onSelectWorker:(worker:Worker)=>void; onSelectCategory:(category:string)=>void; citizenName:string; citizenAddress:string; onOpenProfile?:()=>void; }
const POPULAR=['Electrician','Plumber','Carpenter','AC Technician','Cleaner/Housekeeper','Painter'];

export default function CitizenHomeCatalog({onTransition,onSelectCategory,citizenName,citizenAddress,onOpenProfile}:Props){
  const [query,setQuery]=useState(''); const [area,setArea]=useState('Choose your location'); const [areaAddress,setAreaAddress]=useState(''); const [residential,setResidential]=useState(''); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [searchOpen,setSearchOpen]=useState(false);
  const matches=useMemo(()=>{const q=query.trim().toLowerCase();return PUNCHX_50_CATEGORIES.filter(c=>!q||`${c.name} ${c.shortDesc} ${c.keywords.join(' ')}`.toLowerCase().includes(q));},[query]);
  useEffect(()=>{try{setResidential(localStorage.getItem('punchx_residential_address_label')||citizenAddress||'');}catch{}},[citizenAddress]);
  useEffect(()=>{let cancelled=false;const refresh=async()=>{if(!navigator.geolocation){setMessage('Location is not supported on this device.');return;}setLoading(true);setMessage('Updating service area…');try{const p=await getAccurateCurrentPosition(true);const r=await reverseGeocodeCoords(p.lat,p.lng);if(cancelled)return;const next=r.area||r.city||'Local Area';setArea(next);setAreaAddress(r.address||'');localStorage.setItem('punchx_user_location',JSON.stringify({lat:p.lat,lng:p.lng,area:next,address:r.address,city:r.city,sector:r.sector,timestamp:new Date().toISOString()}));setMessage('Service area updated');}catch{if(!cancelled)setMessage('Choose your service location to continue.');}finally{if(!cancelled)setLoading(false);}};refresh();const onVisible=()=>{if(document.visibilityState==='visible')refresh();};document.addEventListener('visibilitychange',onVisible);return()=>{cancelled=true;document.removeEventListener('visibilitychange',onVisible);};},[]);
  const openCategory=(name:string)=>{setSearchOpen(false);setQuery('');onSelectCategory(name);onTransition('providers');};
  return <div className="punchx-citizen-shell min-h-screen bg-[#f7faff] pb-20 text-[#0f172a]">
    <header className="sticky top-0 z-40 border-b border-[#dbeafe] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-6xl items-center gap-3 px-4 py-2 sm:px-6"><img src={PUNCHX_LOGO} alt="PUNCHX" className="h-9 w-9 rounded-full object-cover border border-[#bfdbfe]"/><span className="text-xl font-black">PUNCHX</span><button onClick={()=>onTransition('customer-setup')} className="ml-1 flex min-w-0 max-w-[55%] items-center gap-2 rounded-xl px-2 py-2 text-left hover:bg-[#f6faff]"><MapPin className="h-4 w-4 shrink-0 text-[#2563eb]"/><span className="min-w-0"><span className="block text-[10px] font-bold uppercase tracking-wider text-[#64748b]">Service area</span><span className="block truncate text-xs font-black">{area}</span></span>{loading&&<Loader2 className="h-4 w-4 animate-spin text-[#2563eb]"/>}</button><button onClick={onOpenProfile} aria-label="Open profile" className="ml-auto flex h-10 items-center gap-2 rounded-xl bg-[#eef6ff] px-3 text-[#0f172a]"><UserRound className="h-4 w-4"/><span className="hidden max-w-28 truncate text-xs font-bold sm:block">{citizenName||'Profile'}</span></button></div><div className="mx-auto flex max-w-6xl items-center gap-2 border-t border-[#eaf2ff] px-4 py-2 sm:px-6"><MapPin className="h-3.5 w-3.5 text-[#2563eb]"/><span className="truncate text-[11px] font-semibold text-[#64748b]">{areaAddress||'Current device area is used for geofencing.'}</span><span className="ml-auto text-[10px] font-bold text-[#2563eb]">{message}</span></div></header>
    <main className="mx-auto max-w-6xl px-4 sm:px-6"><section className="pt-5"><div className="rounded-[28px] bg-gradient-to-br from-[#0f2b55] via-[#173e78] to-[#1e5bb8] p-5 text-white shadow-xl shadow-blue-100 sm:p-8"><div className="flex items-center gap-2 text-xs font-bold text-white/80"><ShieldCheck className="h-4 w-4 text-[#7dd3fc]"/> Verified local professionals</div><h1 className="mt-3 text-3xl font-black sm:text-5xl">What service do you need today?</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/75">Tap search to browse all 50 services. Select a main service to open its facilities and exact work.</p><button type="button" onClick={()=>{setQuery('');setSearchOpen(true);}} className="mt-5 flex w-full items-center gap-2 rounded-2xl bg-white p-2 text-left shadow-xl"><Search className="ml-2 h-5 w-5 text-[#64748b]"/><span className="flex-1 px-1 py-3 text-sm font-semibold text-[#64748b]">Search for a service...</span><span className="rounded-xl bg-[#2563eb] px-4 py-3 text-xs font-black text-white">Search</span></button></div></section>
      <section className="pt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-[#dbeafe] bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#64748b]"><HomeIcon className="h-4 w-4 text-[#2563eb]"/> Residential address</div><div className="mt-2 text-sm font-black">{residential||'Not added yet'}</div><div className="mt-1 text-[10px] text-[#64748b]">Professional visit destination. This does not update the device geofence.</div></div><div className="rounded-2xl border border-[#dbeafe] bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#64748b]"><CalendarDays className="h-4 w-4 text-[#2563eb]"/> Booking flow</div><div className="mt-2 text-sm font-black">Main service → facility → exact work → availability → booking</div><div className="mt-1 text-[10px] text-[#64748b]">Availability is checked only after the final exact work is selected.</div></div></section>
      <section className="pt-7"><div className="flex items-end justify-between"><div><div className="text-[11px] font-bold uppercase tracking-[.16em] text-[#2563eb]">Popular</div><h2 className="mt-1 text-2xl font-black">Popular services</h2></div><button onClick={()=>{setQuery('');setSearchOpen(true);}} className="text-sm font-extrabold text-[#2563eb]">See all 50</button></div><div className="mt-4 grid grid-cols-4 gap-4 sm:grid-cols-6 lg:grid-cols-8">{POPULAR.map((name,index)=>{const category=PUNCHX_50_CATEGORIES.find(item=>item.name===name);const catalog=category?getCatalogCategory(category.id):undefined;return <motion.button key={name} onClick={()=>openCategory(name)} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:index*.06,duration:.35}} whileHover={{y:-4,scale:1.01}} whileTap={{scale:.985}} className="flex flex-col items-center gap-2 text-center group"><div className="relative w-16 h-16 sm:w-20 sm:h-20 bg-[#f4f5f8] rounded-2xl overflow-hidden shadow-sm group-hover:shadow-md transition border border-transparent group-hover:border-[#dbeafe]"><motion.img src={catalog?.image} alt={`${name} service`} className="w-full h-full object-cover p-2 mix-blend-multiply" animate={{scale:[1,1.05,1]}} transition={{duration:3.4+index*.25,repeat:Infinity,ease:'easeInOut',delay:index*.2}}/><div className="absolute bottom-1 left-1/2 -translate-x-1/2 bg-white px-1.5 py-0.5 rounded text-[9px] font-bold text-[#16a34a] shadow-sm border border-[#dcfce7] whitespace-nowrap">45 mins</div></div><div className="text-[11px] sm:text-xs font-semibold leading-tight text-[#334155] line-clamp-2">{name}</div></motion.button>})}</div></section>
      <section className="py-8"><div className="flex items-end justify-between"><div><div className="text-[11px] font-bold uppercase tracking-[.16em] text-[#2563eb]">Complete catalogue</div><h2 className="mt-1 text-2xl font-black">All 50 services</h2></div><button onClick={()=>{setQuery('');setSearchOpen(true);}} className="text-xs font-bold text-[#2563eb]">Open search</button></div><div className="mt-4 grid grid-cols-4 gap-4 sm:grid-cols-6 lg:grid-cols-8">{matches.map((cat,index)=>{const c=getCatalogCategory(cat.id);return <motion.button key={cat.id} onClick={()=>openCategory(cat.name)} initial={{opacity:0,scale:0.95}} animate={{opacity:1,scale:1}} transition={{delay:index*0.03,duration:0.3}} whileHover={{y:-3,scale:1.02}} whileTap={{scale:0.98}} className="flex flex-col items-center gap-2 text-center group"><div className="relative w-16 h-16 sm:w-20 sm:h-20 bg-[#f4f5f8] rounded-2xl overflow-hidden shadow-sm group-hover:shadow-md transition border border-transparent group-hover:border-[#dbeafe]"><img src={c?.image} alt={`${cat.name} service`} className="w-full h-full object-cover p-2 mix-blend-multiply" loading="lazy"/><div className="absolute bottom-1 left-1/2 -translate-x-1/2 bg-white px-1.5 py-0.5 rounded text-[9px] font-bold text-[#16a34a] shadow-sm border border-[#dcfce7] whitespace-nowrap">45 mins</div></div><div className="text-[11px] sm:text-xs font-semibold leading-tight text-[#334155] line-clamp-2">{cat.name}</div></motion.button>})}</div></section>
      <section className="pb-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[#dbeafe] bg-white p-5 shadow-sm"><ShieldCheck className="h-5 w-5 text-[#2563eb]"/><h3 className="mt-3 font-black">Verified professionals</h3><p className="mt-1 text-xs text-[#64748b]">Only approved records can enter matching.</p></div><div className="rounded-2xl border border-[#dbeafe] bg-white p-5 shadow-sm"><CalendarDays className="h-5 w-5 text-[#2563eb]"/><h3 className="mt-3 font-black">Availability after exact work</h3><p className="mt-1 text-xs text-[#64748b]">The unavailable message is not shown before the final service choice.</p></div><div className="rounded-2xl border border-[#dbeafe] bg-white p-5 shadow-sm"><CheckCircle2 className="h-5 w-5 text-[#2563eb]"/><h3 className="mt-3 font-black">Residential visit</h3><p className="mt-1 text-xs text-[#64748b]">The confirmed address is sent to the professional.</p></div></section>
    </main>
    <AnimatePresence>
      {searchOpen&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:0.2}} className="fixed inset-0 z-[130] bg-[#0f172a]/45 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target)setSearchOpen(false)}}><motion.div initial={{opacity:0,scale:0.95,y:10}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:0.95,y:10}} transition={{type:"spring",bounce:0.3,duration:0.4}} className="mx-auto mt-16 flex max-h-[82vh] w-[calc(100%-24px)] max-w-4xl flex-col overflow-hidden rounded-[28px] border border-[#dbeafe] bg-white shadow-2xl sm:mt-20"><div className="flex items-center gap-3 border-b border-[#dbeafe] p-4 sm:p-5"><Search className="h-5 w-5 text-[#2563eb]"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search among all 50 PUNCHX services..." className="min-w-0 flex-1 text-sm font-semibold outline-none"/><span className="hidden rounded-full bg-[#eaf3ff] px-3 py-1 text-[10px] font-black text-[#2563eb] sm:block">{matches.length} services</span><button onClick={()=>setSearchOpen(false)} className="rounded-full bg-[#f1f6ff] p-2"><X className="h-5 w-5"/></button></div><div className="overflow-y-auto p-4 sm:p-5"><div className="mb-4 text-[10px] font-black uppercase tracking-[.16em] text-[#64748b]">Recommended services</div>{matches.length?<div className="grid grid-cols-4 gap-4 sm:grid-cols-6 lg:grid-cols-8">{matches.map((cat,index)=>{const c=getCatalogCategory(cat.id);return <motion.button key={cat.id} onClick={()=>openCategory(cat.name)} initial={{opacity:0,scale:0.9}} animate={{opacity:1,scale:1}} transition={{delay:index*0.02}} whileHover={{y:-3,scale:1.02}} whileTap={{scale:0.98}} className="flex flex-col items-center gap-2 text-center group"><div className="relative w-16 h-16 sm:w-20 sm:h-20 bg-[#f4f5f8] rounded-2xl overflow-hidden shadow-sm group-hover:shadow-md transition border border-transparent group-hover:border-[#dbeafe]"><img src={c?.image} alt={`${cat.name} service`} className="w-full h-full object-cover p-2 mix-blend-multiply" loading="lazy"/><div className="absolute bottom-1 left-1/2 -translate-x-1/2 bg-white px-1.5 py-0.5 rounded text-[9px] font-bold text-[#16a34a] shadow-sm border border-[#dcfce7] whitespace-nowrap">45 mins</div></div><div className="text-[11px] sm:text-xs font-semibold leading-tight text-[#334155] line-clamp-2">{cat.name}</div></motion.button>})}</div>:<div className="py-16 text-center text-sm font-semibold text-[#64748b]">No service matches your search.</div>}</div></motion.div></motion.div>}
    </AnimatePresence>
  </div>;
}
