import React, { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { CalendarDays, ChevronRight, Clock3, MapPin, Navigation2, ShieldCheck, UserRound, X } from 'lucide-react';
import { AppScreen } from '../types';

interface CitizenProfileDrawerProps { isOpen:boolean; onClose:()=>void; onTransition:(screen:AppScreen)=>void; citizenName:string; citizenAddress:string; showNotification:(message:string)=>void; }

export default function CitizenProfileDrawer({isOpen,onClose,onTransition,citizenName,citizenAddress,showNotification}:CitizenProfileDrawerProps){
  const [history]=useState<any[]>(()=>{try{const parsed=JSON.parse(localStorage.getItem('punchx_order_history')||'[]');return Array.isArray(parsed)?parsed:[];}catch{return[];}});
  const activeOrder=useMemo(()=>{try{const raw=localStorage.getItem('punchx_active_order');return raw?JSON.parse(raw):null;}catch{return null;}},[]);
  const go=(screen:AppScreen)=>{onClose();onTransition(screen);};
  return <AnimatePresence>{isOpen&&<div className="fixed inset-0 z-[140] flex items-center justify-center p-4 sm:p-6">
    <motion.button aria-label="Close profile" className="absolute inset-0 bg-black/45 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}/>
    <motion.section role="dialog" aria-modal="true" initial={{opacity:0,scale:.94,y:16}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.94,y:16}} transition={{type:'spring',stiffness:320,damping:30}} className="relative z-10 w-full max-w-md overflow-hidden rounded-[28px] bg-white shadow-[0_25px_100px_rgba(17,18,25,.30)] ring-1 ring-black/10">
      <div className="flex items-center justify-between border-b border-black/5 bg-white px-5 py-4"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-[#7358d7]">Citizen account</div><h2 className="mt-0.5 text-lg font-black">Your PUNCHX profile</h2></div><button onClick={onClose} className="rounded-full bg-[#f3f4f6] p-2" aria-label="Close"><X className="h-5 w-5"/></button></div>
      <div className="max-h-[78vh] space-y-4 overflow-y-auto p-5">
        <section className="rounded-3xl bg-[#f2efff] p-4"><div className="flex items-center gap-3"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#17191d] text-white"><UserRound className="h-6 w-6"/></div><div className="min-w-0 flex-1"><h3 className="truncate text-base font-black">{citizenName||'PUNCHX Citizen'}</h3><p className="mt-1 flex items-center gap-1 text-[10px] text-[#7e828d]"><MapPin className="h-3.5 w-3.5 shrink-0"/><span className="truncate">{citizenAddress||'Residential address not set'}</span></p></div><span className="rounded-full bg-white px-2 py-1 text-[8px] font-black text-[#5b45c7] ring-1 ring-[#7358d7]/10"><ShieldCheck className="mr-1 inline h-3 w-3"/>VERIFIED</span></div></section>
        {activeOrder?.id&&<section className="rounded-3xl bg-[#17191d] p-4 text-white"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-1.5 text-[9px] font-black uppercase tracking-[.14em] text-[#b9adff]"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/>Active service</span><span className="text-[10px] text-white/45">{activeOrder.status||'Processing'}</span></div><h3 className="mt-3 text-base font-black">{activeOrder.category||'Home service'}</h3><p className="mt-1 text-xs text-white/55">{activeOrder.workerName||'Professional assignment pending'}</p><button onClick={()=>go('tracking')} className="mt-4 flex w-full items-center justify-between rounded-2xl bg-white px-4 py-3 text-xs font-black text-[#17191d]">Open live tracking <Navigation2 className="h-4 w-4"/></button></section>}
        <section className="grid grid-cols-2 gap-2.5"><button onClick={()=>go('providers')} className="rounded-2xl border border-black/5 bg-white p-4 text-left shadow-sm ring-1 ring-black/5"><CalendarDays className="h-5 w-5 text-[#7358d7]"/><div className="mt-3 text-sm font-black">Book service</div><div className="mt-1 text-[10px] text-[#8b8f98]">Browse all services</div></button><button onClick={()=>go('tracking')} className="rounded-2xl border border-black/5 bg-white p-4 text-left shadow-sm ring-1 ring-black/5"><Navigation2 className="h-5 w-5 text-[#7358d7]"/><div className="mt-3 text-sm font-black">Track service</div><div className="mt-1 text-[10px] text-[#8b8f98]">Open your active job</div></button></section>
        <section className="rounded-3xl border border-black/5 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.14em] text-[#9296a0]">Order activity</div><div className="mt-1 text-lg font-black">{history.length}</div><div className="text-[10px] text-[#8b8f98]">saved service records</div></div><Clock3 className="h-7 w-7 text-[#7358d7]"/></div><button onClick={()=>showNotification('Your service history is available from the booking records shown in PUNCHX.')} className="mt-4 flex w-full items-center justify-between rounded-xl bg-[#f6f6f8] px-3 py-2.5 text-[10px] font-black text-[#4c5058]">View activity details <ChevronRight className="h-4 w-4"/></button></section>
        <div className="rounded-2xl bg-[#f7f8fa] p-3 text-[10px] leading-5 text-[#7b808a]">Your residential address is used as the professional's visit destination. Device location is used separately for service-area matching.</div>
      </div>
    </motion.section>
  </div>}</AnimatePresence>;
}
